### ISSUE TITLE
Error veryfing ISBN

### ISSUE THREAD

**Issue by katarzynaklimek** [secnot/django-isbn-field#1]
https://www.abebooks.co.uk/9788320708011/dzieci-z-dworca-ZOO-Christiane-832070801X/plp

This books ISBN is rejected by ISBN Field

**Comment by secnot** [comment]
Interesting django-isbn-field just uses stdnum package for validation, and it appear it checks

```python
from stdnum import isbn
isbn.is_valid("9788320708011") # True
isbn.is_valid("832070801X") # True
```
I'll look for the bug tomorrow.

Thank you

**Comment by secnot** [comment]
Just a question, is the second ISBN "832070801X" the one being rejected??

**Comment by katarzynaklimek** [comment]
Yes, the one with the X at the end :)

**Comment by secnot** [comment]
Ok, bug found I'll patch it tomorrow. 

If there are no new problems I'll upload the new version on Pypi in a few days.

**Comment by katarzynaklimek** [comment]
Great, thanks :)

**Comment by katarzynaklimek** [comment]
hi :),
do you know when it will be available on Pypi?

**Comment by secnot** [comment]
Done

**Comment by katarzynaklimek** [comment]
thank you!
